"""Inclusão de campo respondido na tabela contato

Revision ID: 91df271d80f5
Revises: 6487760ec434
Create Date: 2024-05-16 11:19:49.422039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91df271d80f5'
down_revision = '6487760ec434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
